name: Dolebas Config
type: module
description: Takes care of configuration
core: 8.x
configure: dolebas_config.config
package: Dolebas
dependencies:
  - drupal:contact
  - drupal:telephone
  - drupal:link
  - drupal:filter
  - drupal:path
  - smtp:smtp
  - exclude_node_title:exclude_node_title
  - drupal:views
  - mailsystem:mailsystem
  - url_redirect:url_redirect
  - address:address
  - views_contextual_filters_or:views_contextual_filters_or
  
