name: Dolebas Config
type: module
description: Takes care of configuration
core: 8.x
configure: dolebas_config.config
package: Dolebas
dependencies:
  - smtp:smtp
  - exclude_node_title:exclude_node_title
  - drupal:views