module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  breakpoint: 0
  config: 0
  dblog: 0
  default_content: 0
  dolebas_default_content: 0
  dynamic_page_cache: 0
  field: 0
  file: 0
  file_entity: 0
  filter: 0
  hal: 0
  image: 0
  node: 0
  page_cache: 0
  rest: 0
  serialization: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views: 0
  minimal: 1000
theme:
  stark: 0
  bootstrap: 0
  dolebas_subtheme: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
